<?php

return [
    'sp' => [
        // Our entity ID, shared by all clients
        'entity_id' => env('SAML_SP_ENTITY_ID', env('APP_URL', 'http://localhost').'/saml/metadata'),
        // PEM file paths; local pair is generated by `make env`, prod pair
        // lives in the deploy environment. Never committed.
        'cert_path' => env('SAML_SP_CERT_PATH', storage_path('saml/sp.crt')),
        'key_path' => env('SAML_SP_KEY_PATH', storage_path('saml/sp.key')),
    ],

    // Cache store + TTL for assertion-ID replay protection
    'replay_store' => env('SAML_REPLAY_STORE', 'redis'),
    'replay_ttl' => env('SAML_REPLAY_TTL', 300),
];
