<?php

return [
    'sp' => [
        // No shared entity ID: each client's entity ID is its metadata URL
        // (SamlSettingsFactory), so one customer tenant can register several
        // clients — Entra enforces Identifier uniqueness per tenant.
        // PEM file paths; local pair is generated by `make env`, prod pair
        // lives in the deploy environment. Never committed.
        'cert_path' => env('SAML_SP_CERT_PATH', storage_path('saml/sp.crt')),
        'key_path' => env('SAML_SP_KEY_PATH', storage_path('saml/sp.key')),
    ],

    // Cache store + TTL for assertion-ID replay protection
    'replay_store' => env('SAML_REPLAY_STORE', 'redis'),
    'replay_ttl' => env('SAML_REPLAY_TTL', 300),

    // Admin portal SSO handoff (docs/specs/2026-07-09-admin-portal-sso.md)
    'admin_portal_url' => env('ADMIN_PORTAL_URL', 'https://www.apexinnovations.com/admin'),
    'admin_handoff_ttl' => env('ADMIN_HANDOFF_TTL', 60),
];
