#!/bin/bash
set -ex

yum update -y 
yum install -y httpd httpd-tools mod_ssl git
yum install amazon-linux-extras -y

amazon-linux-extras enable php7.4 
yum clean metadata 
yum -y install php php-common php-pear php-pecl-redis
yum -y install php-{cgi,curl,mbstring,gd,mysqlnd,gettext,json,xml,fpm,intl,zip} 
php -v






