name: Deploy
on:
  push:
    branches:
      - master

concurrency:
  group: prod
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Composer
      run: composer update --working-dir ${{ github.workspace }}/
      
  docker-php:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: login to ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 685265542736.dkr.ecr.us-east-1.amazonaws.com
    - name: dockerignore
      run: cp .dockerignore-php .dockerignore
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-php
        push: true
        tags: apexinnovations-php-fpm-login 685265542736.dkr.ecr.us-east-1.amazonaws.com/apexinnovations-php-fpm-login
    
    - name: Docker push
      run: docker push 685265542736.dkr.ecr.us-east-1.amazonaws.com/apexinnovations-php-fpm-login
